import Head from "next/head";
import Hero from "../components/hero";

// import { api } from "~/utils/api";
import NavBar from "~/components/navBar";

export default function Home() {

  return (
    <>
      <Head>
        <title>Fresh by Bell</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-h-screen">
        <Hero />
        <NavBar />
      </main>
    </>
  );
}
